name: Draft PDF

on:
  push:
    paths:
      - Manuscript/paper.md
      - Manuscript/paper.bib
      - .github/workflows/draft-pdf.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: Manuscript/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: Manuscript/paper.pdf
